name: Extract all .car files with Asset Catalog Tinkerer (fixed)

on:
  workflow_dispatch:

jobs:
  extract-all:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Asset Catalog Tinkerer (Homebrew cask)
        run: |
          brew update
          brew install --cask asset-catalog-tinkerer || brew reinstall --cask asset-catalog-tinkerer
          ls -la /Applications | grep -i "Asset Catalog" || true

      - name: Extract every Assets/*.car to Assets/<basename>/
        run: |
          set -euo pipefail

          # Point to the act binary (no escaped spaces)
          ACT_BIN="/Applications/Asset Catalog Tinkerer.app/Contents/MacOS/act"

          if [ ! -x "$ACT_BIN" ]; then
            echo "act binary not found at: $ACT_BIN"
            echo "Listing app bundle contents for debugging:"
            ls -la "/Applications/Asset Catalog Tinkerer.app/Contents/MacOS" || true
            exit 1
          fi

          echo "Using act binary: $ACT_BIN"
          shopt -s nullglob

          found=0
          for car in Assets/*.car; do
            found=1
            base="$(basename "$car" .car)"
            out="Assets/${base}"
            mkdir -p "$out"
            echo "==== Extracting $car -> $out ===="

            # Save info.json (metadata)
            "$ACT_BIN" --input "$car" info > "$out/info.json" 2>/dev/null || true

            # Try the most-likely extract invocations; stop when one works
            # 1) act --input <car> extract <out>
            if "$ACT_BIN" --input "$car" extract "$out" 2>/dev/null; then
              echo "Succeeded: act --input <car> extract <out>"
            # 2) act --input <car> extract --output <out>
            elif "$ACT_BIN" --input "$car" extract --output "$out" 2>/dev/null; then
              echo "Succeeded: act --input <car> extract --output <out>"
            # 3) act --input <car> extract -o <out>
            elif "$ACT_BIN" --input "$car" extract -o "$out" 2>/dev/null; then
              echo "Succeeded: act --input <car> extract -o <out>"
            # 4) fallback: try calling extract without --input (older/newer cli variants)
            elif "$ACT_BIN" extract "$car" "$out" 2>/dev/null; then
              echo "Succeeded: act extract <car> <out>"
            else
              echo "All automatic extract attempts failed for $car."
              echo "Printing act extract help to logs:"
              # attempt to print subcommand help in several ways
              "$ACT_BIN" --input "$car" extract --help 2>/dev/null || "$ACT_BIN" extract --help 2>/dev/null || "$ACT_BIN" --help 2>/dev/null || true
            fi

            echo "Contents of $out (first 200 lines):"
            ls -la "$out" | sed -n '1,200p' || true
          done

          if [ "$found" -eq 0 ]; then
            echo "No .car files found in Assets/ — make sure you committed them to the repo path Assets/*.car"
          fi

      - name: Upload extracted folders as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted-assets
          path: |
            Assets/*
